import Head from 'next/head'
import { useState } from 'react';

const AddSongs = () => {
    const [title, setTitle] = useState('');
    const [artist, setArtist] = useState('');
    const [source, setSource] = useState(null);
    const onSubmit = async (e) => {
        e.preventDefault();
        console.log(title, artist, source.name, source.type, source);
        const song = {
            "file": source,
            "filename": source.name,
            "mimetype": source.type
        }
        const formdata = new FormData();
        formdata.append('title', title);
        formdata.append('artist', artist);
        formdata.append('file', source);

        const message = await fetch('http://localhost:8000/api/songs/',
            {
                method: 'POST',
                body: formdata,
            });
        console.log(message)
    }
    return <div>
        <Head>
            <title>Artist App - Add Songs</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className='grid place-items-center'>
            <form onSubmit={onSubmit}>
                <div className="form-control w-full max-w-xs">
                    <label className="label">
                        <span className="label-text">Title</span>
                    </label>
                    <input type="text"
                        placeholder="Type here"
                        className="input input-bordered w-full max-w-xs"
                        value={title} onChange={e => setTitle(e.target.value)} />
                </div>
                <div className="form-control w-full max-w-xs">
                    <label className="label">
                        <span className="label-text">Artist</span>
                    </label>
                    <input type="text"
                        placeholder="Type here"
                        className="input input-bordered rounded w-full max-w-xs"
                        value={artist} onChange={e => setArtist(e.target.value)} />
                </div>
                <div className="form-control w-full max-w-xs">
                    <label htmlFor="formFile" className="label  inline-block mb-2 text-gray-700">
                        <span className='label-text'>Default file input example</span>
                    </label>
                    <input className="w-full px-3 py-1.5 text-base
                                   text-gray-700 bg-white bg-clip-padding
                                    border border-solid border-gray-300
                                    rounded"
                        type="file" id="formFile"
                        onChange={(e) => setSource(e.target.files[0])} />
                </div>
                <button type='submit' className='btn btn-primary'>Submit</button>
            </form>

        </div>
        {/* <FillerStats /> */}

    </div>;
};
export default AddSongs;