import Head from 'next/head'
import { useState, useRef } from 'react';

const AddSongs = () => {
    const [title, setTitle] = useState('');
    const [artist, setArtist] = useState('');
    const [audio, setAudio] = useState(null);
    const [coverImage, setCoverImage] = useState('');

    const ref = useRef();



    const onSubmit = async (e) => {
        e.preventDefault();

        const formdata = new FormData();
        formdata.append('title', title);
        formdata.append('artist', artist);
        formdata.append('coverImage', coverImage);
        formdata.append('audio', audio);

        const message = await fetch('http://localhost:8000/api/songs/',
            {
                method: 'POST',
                body: formdata,
            });
        console.log(message)

        setTitle('');
        setArtist('');
        setAudio(null);
        setCoverImage('');
        ref.current.value = ""
    }



    return <div>
        <Head>
            <title>Artist App - Add Songs</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className='grid place-items-center'>
            <form onSubmit={onSubmit}>
                <div className="form-control w-full max-w-xs">
                    <label className="label">
                        <span className="label-text">Title</span>
                    </label>
                    <input type="text"
                        placeholder="Type here"
                        className="input input-bordered w-full max-w-xs"
                        value={title} onChange={e => setTitle(e.target.value)} />
                </div>

                <div className="form-control w-full max-w-xs">
                    <label className="label">
                        <span className="label-text">Artist</span>
                    </label>
                    <input type="text"
                        placeholder="Type here"
                        className="input input-bordered rounded w-full max-w-xs"
                        value={artist} onChange={e => setArtist(e.target.value)} />
                </div>

                <div className="form-control w-full max-w-xs">
                    <label className="label">
                        <span className="label-text">Cover Image URL</span>
                    </label>
                    <input type="text"
                        placeholder="Type here"
                        className="input input-bordered rounded w-full max-w-xs"
                        value={coverImage} onChange={e => setCoverImage(e.target.value)} />
                </div>

                <div className="form-control w-full max-w-xs">
                    <label htmlFor="formFile" className="label  inline-block mb-2 text-gray-700">
                        <span className='label-text'>Default file input example</span>
                    </label>
                    <input className="w-full px-3 py-1.5 text-base
                                   text-gray-700 bg-white bg-clip-padding
                                    border border-solid border-gray-300
                                    rounded"
                        ref={ref}
                        type="file" id="formFile"
                        onChange={(e) => setAudio(e.target.files[0])} />
                </div>
                <button type='submit' className='btn btn-primary my-8 w-full'>Submit</button>
            </form>

        </div>

    </div>;
};
export default AddSongs;