import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Navbar from '../components/Navbar';
import Songs from '../components/Songs';
import FillerStats from '../components/FillerStats';

export default function Home() {

  return (
    <div>
      <Head>
        <title>Artist App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Songs />
      <FillerStats />
      {/* add playlists */}
    </div>
  )
}

