import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Navbar from '../components/Navbar';
import Songs from '../components/Songs';
import Playlists from '../components/Playlists';
import * as React from 'react';


export default function Home() {

  return (
    <div>
      <Head>
        <title>Artist App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='grid grid-cols-4 gap-16'>
        <Playlists />
        <Songs />
      </div>
    </div>
  )
}

