import Head from 'next/head'
import styles from '../styles/Home.module.css'

import Navbar from '../components/Navbar';
import Songs from '../components/Songs';
import Playlists from '../components/Playlists';
import { useEffect } from 'react';


export default function Home() {
  useEffect(() => {
    fetch('http://localhost:8000/api/songs/').then(res => res.json()).then(data => { console.log(data) })
  }, []);
  return (
    <div>
      <Head>
        <title>Artist App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='grid grid-cols-4 gap-16'>
        <Playlists />
        <Songs />
      </div>
      {/* <FillerStats /> */}


    </div>
  )
}

