import Head from 'next/head'
import User from '../components/User'
import styles from '../styles/Home.module.css'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Spotify Clone App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <User />

      {/* Get Songs */}
      {/* Like Songs Button which can add a song to user's liked songs array */}


    </div>
  )

}
export const getStaticProps = async context => {
  return {
    props: {},
  };
};