@hostname=http://localhost:8000

get {{hostname}}/api/songs/

###

POST {{hostname}}/api/songs/ 
Content-Type: application/json

{
  "title": "title4",
  "artist": "artist3",
  "album": "album",
  "genre": "genre",
  "year": "year",
  "track": "track",
  "duration": "duration",
  "bitrate": "bitrate",
  "size": "size",
  "file": "file"
}
###

PUT {{hostname}}/api/songs/62c13720bde41a63143fe53e
Content-Type: application/json

{
  
  "title": "file"
}
###
delete {{hostname}}/api/songs/62c137b26e394e79c095dc62